fix overlay coords
arslee07/pb pull request #9
Opened 2022-08-01 16:31 UTC by Calamity34

simple, innit?

2022-08-01 16:47 UTC, Calamity34 commented
that should fix #7

2022-08-01 16:48 UTC, arslee07 requested changes

2022-08-01 16:48 UTC, arslee07 commented on pb-web/src/App.js
> +          <div className="py-1 px-2 rounded mb-2 bg-primary text-white">({coords.x-1}; {coords.y-1})</div>
мне кажется что он где-то в другой части кода прибавляет 1 к кордам

2022-08-01 16:48 UTC, arslee07 commented on pb-web/src/App.js
> +          <div className="py-1 px-2 rounded mb-2 bg-primary text-white">({coords.x-1}; {coords.y-1})</div>
ну и типа лучше будет из той части убрать инкремент, чем здесь уменьшать число

2022-08-01 16:50 UTC, voidlynx commented on pb-web/src/App.js
> +          <div className="py-1 px-2 rounded mb-2 bg-primary text-white">({coords.x-1}; {coords.y-1})</div>
я полистал, там эта вещь вроде вообще за систему плейсмента пикселей отвечает, тут чутка поуютнее

опять же, если найду что-то, пофикшу. for now afk.

2022-08-01 16:52 UTC, arslee07 commented on pb-web/src/App.js
> +          <div className="py-1 px-2 rounded mb-2 bg-primary text-white">({coords.x-1}; {coords.y-1})</div>
https://github.com/Calamity34/pb/blob/7d602fd18e4d24705fac6f3990a33c12763ccd89/pb-web/src/components/InteractionCanvas.js#L44

вот здесь идёт инкремент

2022-08-02 01:09 UTC, arslee07 approved these changes

2022-08-02 01:09 UTC, arslee07 commented
ok lgtm

2022-08-02 01:10 UTC, merged